# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a187a3594cc2b37b14e66a419813793446a1bf0a9a352a61f8b3149c800947d099f19423c82a751e8359b72ef9320815d036c5ef1b85cea8fec6cd6006f69d5d

test:
  secret_key_base: 176d6b13dc2d58b1df679a56fe8bf663a4cb57ed990395e8ce0d55c4196b93bd0840f49a3d5e8443eb94b5837562b900b82bf9da1f5c2bac3e46b809c77f369c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
